# author 13
# qq-group 791509631
# email 2449207463@qq.com
# link https://github.com/newbee-ltd

# 服务器配置
server:
  port: 28079
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256

# 项目全局配置
project:
  name: newbee-mall-plus # 项目名称
  #  fileUploadPath: /opt/newbee-mall-plus/upload/  # 上传文件的默认url前缀，根据部署设置自行修改，linux下路径
  fileUploadPath: D:\\upload\\              # 上传文件的默认url前缀，根据部署设置自行修改，windows下路径
  orderUnpaidOverTime: 300 # 订单未支付超期时间，单位秒
  serverUrl: http://localhost:28079 # 服务器地址

# spring配置
spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: @activatedProperties@

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    # mapper映射文件位置

# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
alipay:
  app-id:
  rsa-private-key:
  alipay-public_key:
  gateway: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  #  log-path: /opt/newbee-mall-plus/log
  log-path: D://newbee-mall-plus//log
  signtype: RSA2
